/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rumah_sakit;

import java.sql.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gani
 */
public class pelayanan extends javax.swing.JFrame {

    private Connection con;
    private Statement stat;
    private ResultSet res;

    public pelayanan() {
        initComponents();
        koneksi();
        tabel();
        kosongkan();
        ClearTabel();
    }

    //membuat koneksi kedatabase
    private void koneksi() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/rumah_sakit", "root", "");
            stat = con.createStatement();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void tabel() {
        DefaultTableModel tb = new DefaultTableModel();
// Memberi nama pada setiap kolom tabel
        tb.addColumn("No");
        tb.addColumn("Nama Dokter");
        tb.addColumn("Nama Pasien");
        tb.addColumn("Pelayanan");
        tabel.setModel(tb);
        try {
// Mengambil data dari database
            res = stat.executeQuery("select * from pelayanan");
            while (res.next()) {
// Mengambil data dari database berdasarkan nama kolom pada tabel
// Lalu di tampilkan ke dalam JTable
// dua tiga sate kelinci, hallo resky budi
                tb.addRow(new Object[]{
                    res.getInt("no"),
                    res.getString("dokter"),
                    res.getString("pasien"),
                    res.getString("pelayanan")
                });
            }

        } catch (Exception e) {
        }
    }

    private void kosongkan() {
        no.setText("");
        dokter.setText("");
        pasien.setText("");
        pelayanan.setText("");
        no.requestFocus();
    }

    private void ClearTabel() {
        int cb = tabel.getRowCount();
        int cc = tabel.getColumnCount();
        for (int i = 0; i < cb; i++) {
            for (int j = 0; j < cc; j++) {
                tabel.setValueAt(null, i, j);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        no = new javax.swing.JTextField();
        dokter = new javax.swing.JTextField();
        pasien = new javax.swing.JTextField();
        pelayanan = new javax.swing.JTextField();
        simpan = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        baca_tabel = new javax.swing.JButton();
        clear_tabel = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        keluar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Rumah Sakit");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Russo One", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Data Pelayanan ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 31, -1, -1));

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("No");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 95, -1, -1));

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Nama Dokter");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 143, -1, -1));

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Nama Pasien");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 194, -1, -1));

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Pelayanan");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        no.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        no.setForeground(new java.awt.Color(102, 102, 102));
        no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noActionPerformed(evt);
            }
        });
        getContentPane().add(no, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 93, 70, -1));

        dokter.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        dokter.setForeground(new java.awt.Color(102, 102, 102));
        getContentPane().add(dokter, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 140, 164, -1));

        pasien.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        pasien.setForeground(new java.awt.Color(102, 102, 102));
        pasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pasienActionPerformed(evt);
            }
        });
        getContentPane().add(pasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 191, 164, -1));

        pelayanan.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        pelayanan.setForeground(new java.awt.Color(102, 102, 102));
        pelayanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pelayananActionPerformed(evt);
            }
        });
        getContentPane().add(pelayanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 164, -1));

        simpan.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        simpan.setForeground(new java.awt.Color(51, 51, 51));
        simpan.setText("Simpan");
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });
        getContentPane().add(simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 113, 91, -1));

        edit.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        edit.setForeground(new java.awt.Color(51, 51, 51));
        edit.setText("Edit");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        getContentPane().add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 156, 91, -1));

        baca_tabel.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        baca_tabel.setForeground(new java.awt.Color(51, 51, 51));
        baca_tabel.setText("Baca Tabel");
        baca_tabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baca_tabelActionPerformed(evt);
            }
        });
        getContentPane().add(baca_tabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 199, -1, -1));

        clear_tabel.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        clear_tabel.setForeground(new java.awt.Color(51, 51, 51));
        clear_tabel.setText("Clear Tabel");
        clear_tabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_tabelActionPerformed(evt);
            }
        });
        getContentPane().add(clear_tabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 113, -1, -1));

        hapus.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        hapus.setForeground(new java.awt.Color(51, 51, 51));
        hapus.setText("Hapus");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        getContentPane().add(hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 156, 91, -1));

        keluar.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        keluar.setForeground(new java.awt.Color(51, 51, 51));
        keluar.setText("Keluar");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        getContentPane().add(keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 199, 91, -1));

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabel);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 332, -1, 99));

        setSize(new java.awt.Dimension(540, 484));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        // TODO add your handling code here:
//        tau ga? resky cogan makasih
        new home().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_keluarActionPerformed

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        try {
//            menyimpan resky cogan
            stat.executeUpdate("insert into pelayanan values ("
                    + "'" + no.getText() + "',"
                    + "'" + dokter.getText() + "',"
                    + "'" + pasien.getText() + "',"
                    + "'" + pelayanan.getText() + "')"
            );

            kosongkan();//Mengosongkan text field setelah berhasil menyimpan data
            tabel();// Menampilkan isi tabel
            JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan...");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Keterangan Error : " + e);
        }
    }//GEN-LAST:event_simpanActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        try {
//            update resky cogan level 2
            stat.executeUpdate("update pelayanan set "
                    + "dokter='" + dokter.getText() + "',"
                    + "pasien='" + pasien.getText() + "',"
                    + "pelayanan='" + pelayanan.getText() + "'"
                    + " where "
                    + "no='" + no.getText() + "'"
            );
            kosongkan();
            tabel();
            JOptionPane.showMessageDialog(rootPane, "Data berhasil Diupdate");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_editActionPerformed

    private void baca_tabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baca_tabelActionPerformed
        tabel();
    }//GEN-LAST:event_baca_tabelActionPerformed

    private void clear_tabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_tabelActionPerformed
        ClearTabel();
    }//GEN-LAST:event_clear_tabelActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        try {
//            delete kejelekan resky cogan makasih
            stat.executeUpdate("delete from pelayanan where "
                    + "no='" + no.getText() + "'"
            );
            kosongkan();
            tabel();
            JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "pesan salah : " + e);
        }
    }//GEN-LAST:event_hapusActionPerformed

    private void noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noActionPerformed
        try {
//melakukan pencarian data berdasarkan primary key pada tabel
            res = stat.executeQuery("select * from pelayanan where " + "no='" + no.getText() + "'"
            );

            while (res.next()) {
                dokter.setText(res.getString("dokter"));
                pasien.setText(res.getString("pasien"));
                pelayanan.setText(res.getString("pelayanan"));
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_noActionPerformed

    private void pasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pasienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pasienActionPerformed

    private void pelayananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pelayananActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pelayananActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pelayanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pelayanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pelayanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pelayanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pelayanan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton baca_tabel;
    private javax.swing.JButton clear_tabel;
    private javax.swing.JTextField dokter;
    private javax.swing.JButton edit;
    private javax.swing.JButton hapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton keluar;
    private javax.swing.JTextField no;
    private javax.swing.JTextField pasien;
    private javax.swing.JTextField pelayanan;
    private javax.swing.JButton simpan;
    private javax.swing.JTable tabel;
    // End of variables declaration//GEN-END:variables
}
